#pragma once

#ifndef MQTT_MAX_PAYLOAD_LENGTH
    #define MQTT_MAX_PAYLOAD_LENGTH 512
#endif

#ifndef MQTT_MAX_CLIENT_ID_LENGTH
    #define MQTT_MAX_CLIENT_ID_LENGTH 23
#endif

#ifndef MQTT_MAX_CONNECT_PROPERTY_COUNT
    #define MQTT_MAX_CONNECT_PROPERTY_COUNT 8
#endif

#ifndef MQTT_MAX_CONNACK_PROPERTY_COUNT
    #define MQTT_MAX_CONNACK_PROPERTY_COUNT 17
#endif

#ifndef MQTT_MAX_WILL_PROPERTY_COUNT
    #define MQTT_MAX_WILL_PROPERTY_COUNT 8
#endif

#ifndef MQTT_MAX_PUBLISH_PROPERTY_COUNT
    #define MQTT_MAX_PUBLISH_PROPERTY_COUNT 7
#endif

#ifndef MQTT_MAX_PUBLISH_PAYLOAD_LENGTH
    #define MQTT_MAX_PUBLISH_PAYLOAD_LENGTH 1024
#endif

#ifndef MQTT_MAX_PUBACK_PROPERTY_COUNT
    #define MQTT_MAX_PUBACK_PROPERTY_COUNT 3
#endif

#ifndef MQTT_MAX_SUBSCRIBE_PROPERTY_COUNT
    #define MQTT_MAX_SUBSCRIBE_PROPERTY_COUNT 3
#endif

#ifndef MQTT_MAX_DISCONNECT_PROPERTY_COUNT
    #define MQTT_MAX_DISCONNECT_PROPERTY_COUNT 4
#endif

#ifndef MQTT_MAX_AUTH_PROPERTY_COUNT
    #define MQTT_MAX_AUTH_PROPERTY_COUNT 4
#endif

#ifndef MQTT_MAX_SUBSCRIBE_TOPIC_COUNT
    #define MQTT_MAX_SUBSCRIBE_TOPIC_COUNT 3
#endif

#ifndef MQTT_MAX_PROPERTY_LENGTH
    #if MQTT_MAX_CLIENT_ID_LENGTH > 32
        #define MQTT_MAX_PROPERTY_LENGTH MQTT_MAX_CLIENT_ID_LENGTH
    #else
        #define MQTT_MAX_PROPERTY_LENGTH 32
    #endif
#endif

#ifndef MQTT_MAX_BINARY_DATA_LENGTH
    #define MQTT_MAX_BINARY_DATA_LENGTH 64
#endif

#ifndef MQTT_VERSION
    #define MQTT_VERSION 5
#endif

#ifndef MQTT_MAX_WILL_PAYLOAD_LENGTH
    #define MQTT_MAX_WILL_PAYLOAD_LENGTH 16
#endif

#ifndef MQTT_MAX_USERNAME_LENGTH
    #define MQTT_MAX_USERNAME_LENGTH 16
#endif

#ifndef MQTT_MAX_PASSWORD_LENGTH
    #define MQTT_MAX_PASSWORD_LENGTH 16
#endif

#ifndef MQTT_MAX_TOPIC_NAME_LENGTH
    #define MQTT_MAX_TOPIC_NAME_LENGTH 16
#endif